# Generated by Django 3.0.1 on 2020-01-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='address_2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
