# Generated by Django 3.0.1 on 2020-01-19 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('short', models.CharField(max_length=16)),
                ('internal_name', models.CharField(max_length=32)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(max_length=128)),
                ('zipcode', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('level', models.CharField(max_length=8)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Dorm')),
            ],
        ),
    ]
