# Generated by Django 3.0.1 on 2020-01-19 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('iban', models.CharField(max_length=34)),
                ('bic', models.CharField(max_length=11)),
                ('dorm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Dorm')),
                ('treasurer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64, verbose_name='receipt_name')),
                ('document', models.FileField(upload_to='receipts/', verbose_name='receipt_document')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='transaction_state_name')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='transaction_tag_name')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation_date')),
                ('subject', models.CharField(max_length=128, verbose_name='transaction_subject')),
                ('date', models.DateTimeField(verbose_name='transaction_date')),
                ('sender', models.CharField(max_length=64)),
                ('receiver', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Account')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Receipt', verbose_name='transaction_receipt')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.State')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.Tag')),
            ],
        ),
    ]
